<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Cusimano">
<meta name="dcterms.date" content="2023-03-30">

<title>Palmer Penguins Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="exploratory_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="exploratory_analysis_files/libs/quarto-html/quarto.js"></script>
<script src="exploratory_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="exploratory_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exploratory_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="exploratory_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exploratory_analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exploratory_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exploratory_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exploratory_analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Palmer Penguins Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel Cusimano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 30, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="source-data-and-code" class="level3">
<h3 class="anchored" data-anchor-id="source-data-and-code">Source Data and Code</h3>
<p>This Quarto file loads the results of a multivariate morphological analysis of the Palmer Penguins dataset. The data used for this project was previous cleaned by the author and can be accessed through https://github.com/cusisom/cusimano-rclass-project. In addition to the original data and r code for cleaning and analysis, this github site contains all of the figures and tables used in this summary as well as the finished manuscript for the project. For more information on the associated repo, follow the link provided above and refer to the site README.</p>
<p>While the script for used by this Quarto file contains all of the analysis, the analysis script has also been segmented into four distinct sections in the <code>Code_sections</code> folder for individual review (Data Summary, Body Mass Analysis, Sexual Dimorphism, and Analysis of Variance). These sections are also clearly delineated in the primary analysis code (analysiscode.R).</p>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<p>The focus of this study is one morphological variation in the three penguin species reviewed in the dataset. While the first section of this overview details a summary of all of the Palmer Penguins data, the following sections omit information which pertains to Carbon 13 and Nitrogen 15.</p>
<p>The primary sections of this review pertain to three interrelated research questions. These sections/questions are as follows:</p>
<pre><code>I. Body Mass Distribution: Identifying areaas of Interspecific and Intraspecific Variation

II. Analysis of Sexual Dimorphism

III. Differentiating between Adelie and Chinstrap penguins. Shape Profile Analysis</code></pre>
<p>####<em>Note about statistics</em></p>
<p><em>Much of the difficulty experienced throughout this project comes from the author’s lack of statistical training. I opted to take this course this term instead of a statistics course due to unlikely event of it being offered again during my time at UH. While I did my best to apply the necessary statistical analyses and appropriately interpret the results, I am not currently confident in my application.</em></p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<p>To run this R script, users must install and require a variety of packages. Our template for this project included some of what is seen below but packages such as <code>report()</code>, <code>patchwork()</code>, and <code>Ggally()</code> were added by the author. There are many new file paths also developed by the author to funnel the various analysis products to the right location.</p>
<p>Finally, as was done for the data cleaning output, this quarto makes use of code chunks and therefore required the use of the knitr read chunk function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">'analysiscode.R'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load needed packages and filepaths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load needed packages. make sure they are installed.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(ggplot2) <span class="co">#for plotting</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(magrittr) <span class="co">#for piping</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(knitr) <span class="co">#for formatting output</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(dplyr) </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(report)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(patchwork) <span class="co">#for grouping plots together</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(GGally)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#path to data and results </span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"../../Data/Processed_data/"</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>results_path <span class="ot">&lt;-</span> <span class="st">"../../Results/"</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>figures_path <span class="ot">&lt;-</span> <span class="st">"../../Results/Figures/"</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>stats_path <span class="ot">&lt;-</span> <span class="st">"../../Results/Statistics/"</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>PC_path <span class="ot">&lt;-</span> <span class="st">"../../Results/Statistics/Princomp/"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load custom function to facilitate efficient path funneling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function to paste path to output filenames</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>addpath <span class="ot">&lt;-</span> <span class="cf">function</span>( filename, <span class="at">path=</span>data_path ) {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    location <span class="ot">&lt;-</span> <span class="fu">paste</span>( path, filename, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>( location )</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Load the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data. </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">readRDS</span>( <span class="fu">addpath</span>(<span class="st">"penguins.rds"</span>, data_path) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary-table" class="level1">
<h1>Summary Table</h1>
<p>With the data cleaned in the last project, it is worth displying here the information that is being worked with in this analysis. For ease of access and brief review, I am utilizing the skimr function but setting the information up in a dataframe ratherr than a tibble. With this I can more easily illustrate different chunks of information.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">'Data_Summary.R'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create summary table of the data using skimr to use in paper</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># variables, sample size, mean, standard error</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>sk <span class="ot">&lt;-</span> skimr<span class="sc">::</span><span class="fu">skim</span>(dat)  <span class="co"># save skim object</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>sk <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(sk) <span class="co"># save as data.frame</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sk)  <span class="co"># see the variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  skim_type  skim_variable n_missing complete_rate factor.ordered
1    factor        Species         0     1.0000000          FALSE
2    factor         Island         0     1.0000000          FALSE
3    factor            Sex         9     0.9734513          FALSE
4   numeric  Culmen Length         0     1.0000000             NA
5   numeric   Culmen Depth         0     1.0000000             NA
6   numeric Flipper Length         0     1.0000000             NA
  factor.n_unique           factor.top_counts numeric.mean numeric.sd
1               3 Ade: 151, Gen: 120, Chi: 68           NA         NA
2               3 Bis: 164, Dre: 124, Tor: 51           NA         NA
3               2          MAL: 168, FEM: 162           NA         NA
4              NA                        &lt;NA&gt;     43.89705   5.470566
5              NA                        &lt;NA&gt;     17.17345   1.968781
6              NA                        &lt;NA&gt;    200.79056  14.054430
  numeric.p0 numeric.p25 numeric.p50 numeric.p75 numeric.p100 numeric.hist
1         NA          NA          NA          NA           NA         &lt;NA&gt;
2         NA          NA          NA          NA           NA         &lt;NA&gt;
3         NA          NA          NA          NA           NA         &lt;NA&gt;
4       32.1       39.20        44.4        48.5         59.6        ▅▇▇▆▁
5       13.1       15.65        17.3        18.7         21.5        ▅▅▇▇▂
6      172.0      190.00       197.0       213.0        231.0        ▂▇▃▅▂</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nrows <span class="ot">&lt;-</span> <span class="fu">dim</span>(dat)[<span class="dv">1</span>] <span class="co"># total number of rows</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sk<span class="sc">$</span>N <span class="ot">&lt;-</span> nrows <span class="sc">-</span> sk<span class="sc">$</span>n_missing  <span class="co"># sample size of each variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="publishing-summary-table" class="level2">
<h2 class="anchored" data-anchor-id="publishing-summary-table">Publishing Summary Table</h2>
<p>While the above summary data is informative and useful for this overview, it is not in a format that is ready for publication. Using the following code, I am able to specify the summary statistics that are most useful for quick reference, rename the columns, and, using <code>knitr</code>, transform the table into a presentation format. This will be combined with the <code>results=asis</code> command to maintain a polished format when applicable.</p>
<p><em>Note-</em></p>
<p><em>I tried applying the knitr.kable method for some of my analytical results but it would change some of the values. I’m sure there is some coding trick to make this work better, I couldn’t quite figure it out.</em></p>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select only the variable, N, mean, sd, and category counts</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>sk.table <span class="ot">&lt;-</span> sk[<span class="fu">c</span>(<span class="st">"skim_variable"</span>, <span class="st">"N"</span>, <span class="st">"numeric.mean"</span>, <span class="st">"numeric.sd"</span>, <span class="st">"factor.top_counts"</span>)]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(sk.table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"N"</span>, <span class="st">"Mean"</span>, <span class="st">"SE"</span>, <span class="st">"Counts"</span>) <span class="co"># rename SD as SE</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>sk.table<span class="sc">$</span>SE <span class="ot">&lt;-</span> sk.table<span class="sc">$</span>SE<span class="sc">/</span><span class="fu">sqrt</span>(sk.table<span class="sc">$</span>N) <span class="co"># calculate SE</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">knitr.kable.NA =</span> <span class="st">""</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(sk.table, <span class="at">digits=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: left;">Counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Species</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Ade: 151, Gen: 120, Chi: 68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Island</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">Bis: 164, Dre: 124, Tor: 51</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sex</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: left;">MAL: 168, FEM: 162</td>
</tr>
<tr class="even">
<td style="text-align: left;">Culmen Length</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">43.90</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Culmen Depth</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">17.17</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Flipper Length</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">200.79</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Body Mass</td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">4196.17</td>
<td style="text-align: right;">43.62</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Delta 15 N</td>
<td style="text-align: right;">327</td>
<td style="text-align: right;">8.74</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delta 13 C</td>
<td style="text-align: right;">328</td>
<td style="text-align: right;">-25.68</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save summary table</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(sk.table, <span class="at">file =</span> <span class="fu">addpath</span>(<span class="st">"summary_table.rds"</span>, results_path))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">'Body_Mass_Analysis.R'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="body-mass-distribution" class="level1">
<h1>Body Mass Distribution</h1>
<section id="interspecific-and-intraspecific-varition" class="level2">
<h2 class="anchored" data-anchor-id="interspecific-and-intraspecific-varition">Interspecific and Intraspecific Varition</h2>
<p>We closed out our first project by creating bivariate plots for all of the continuous variables in our dataset. Each of the morhpological data was specifically plotted against body mass to develop an idea of how these features correlated with overall size. This series of plots is designed to summarize that data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate bivariate plot of Culmen Depth~Body Mass</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use geom_smooth to add in the correlation line</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Subtitle instead of title for easier small font</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(dat<span class="sc">$</span><span class="st">'Body Mass'</span>, dat<span class="sc">$</span><span class="st">'Culmen Depth'</span>, <span class="at">color=</span>Species, <span class="at">fill=</span>Species)) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a> <span class="at">subtitle=</span><span class="st">"Body Mass by Culmen Depth"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a> <span class="at">x=</span><span class="st">'Body mass (mm)'</span>, <span class="at">y=</span><span class="st">'Culmen Depth (mm)'</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate bivariate plot of Culmen Length~Body Mass</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(dat<span class="sc">$</span><span class="st">'Body Mass'</span>, dat<span class="sc">$</span><span class="st">'Culmen Length'</span>, <span class="at">color=</span>Species, <span class="at">fill=</span>Species)) <span class="sc">+</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a> <span class="at">subtitle=</span><span class="st">"Body Mass by Culmen Length"</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a> <span class="at">x=</span><span class="st">'Body mass (mm)'</span>, <span class="at">y=</span><span class="st">'Culmen Length (mm)'</span>,</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate bivariate plot of Flipper Length~Body Mass</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(dat<span class="sc">$</span><span class="st">'Body Mass'</span>, dat<span class="sc">$</span><span class="st">'Flipper Length'</span>, <span class="at">color=</span>Species, <span class="at">fill=</span>Species)) <span class="sc">+</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a> <span class="at">subtitle=</span><span class="st">"Body Mass by Flipper Length"</span>,</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a> <span class="at">x=</span><span class="st">'Body mass (mm)'</span>, <span class="at">y=</span><span class="st">'Flipper Length (mm)'</span>,</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate histogram showing the distribution of Body Mass for each species</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> dat<span class="sc">$</span><span class="st">'Body Mass'</span>)) <span class="sc">+</span></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_histogram</span>( <span class="fu">aes</span>(<span class="at">fill=</span>Species), <span class="at">alpha=</span>.<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">subtitle=</span><span class="st">"Body Mass"</span>,</span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">x=</span><span class="st">'Body Mass (g)'</span>, <span class="at">y=</span><span class="st">'Count'</span>,</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">color=</span><span class="st">'Species'</span></span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a> ) </span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a><span class="co">#Show these plots in a single grid.</span></span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a><span class="co">#Allows them to be considered together.</span></span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a><span class="co">#Need specific package to create this layout</span></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(patchwork)</span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a><span class="co">#With patchwork I can use the plus sign (+) to combine the plots in a grid</span></span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a><span class="co">#Specify the number of column you want</span></span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a><span class="co">#Use "collect" to gather the common key for the plots and display it independantly instead of with each. </span></span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a>cor_plots <span class="ot">&lt;-</span> x <span class="sc">+</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3 <span class="sc">+</span> <span class="fu">plot_layout</span>(<span class="at">ncol=</span><span class="dv">2</span>, <span class="at">guides =</span> <span class="st">"collect"</span>)</span>
<span id="cb13-56"><a href="#cb13-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-57"><a href="#cb13-57" aria-hidden="true" tabindex="-1"></a>cor_plots</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/summary_plots-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I am first interested in the size distribution of the Palmer Penguins. I begin by examining the inter- and intraspecific variation in body mass. This is represented in the histogram in the bottom right of the above figure.</p>
<p>This distribution becomes much clearer with the violin plot below. Besides following the pattern seen in the summary plots where the Gentoo Penguins appear to be outliers, it is interesting to observe a seemingly smaller range in body mass for the Chinstrap relative to the Gentoo and Adelie Penguins. My first question concerns this apparent difference in body mass variation for each species. I explore this question by considering the role of sexual dimorphism.</p>
<p>A reasonable explanation for the narrower range in body mass for Chinstrap Penguins would that they reflect less sexual size dimorphism than the other two species. To first test the hypothesis that these three species are indeed sexually dimorphic in body mass I replot the data and distribute it by Sex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(<span class="at">x=</span>Species, <span class="at">y=</span>dat<span class="sc">$</span><span class="st">'Body Mass'</span>, <span class="at">col=</span>Species)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">title=</span><span class="st">"Body Mass by Species"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x=</span><span class="st">'Species'</span>, <span class="at">y=</span><span class="st">'Body Mass (g)'</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">color=</span><span class="st">'Species'</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a> ) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/Dimorphism1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>First I need to remove the NA values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The NA values add an extra variable that complicates the image. Subset out NA's.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>d1 <span class="ot">&lt;-</span> dat[ <span class="sc">!</span><span class="fu">is.na</span>(dat<span class="sc">$</span><span class="st">"Sex"</span>), ]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot the data without NA values to see distribution.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now I can plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> d1 <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Species, <span class="at">y=</span>d1<span class="sc">$</span><span class="st">'Body Mass'</span>, <span class="at">fill=</span>Sex)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_violin</span>(<span class="at">trim=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="at">title=</span><span class="st">"Body Mass by Species and Sex"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="at">x=</span><span class="st">'Sex'</span>, <span class="at">y=</span><span class="st">'Body Mass (g)'</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="at">color=</span><span class="st">'Species'</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>p4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/Dimorphism4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot shows clear dimorphism with Gentoo Penguins. It also illustrates stronger dimorphism in Adelie than Chinstrap populations but it is more subtle. After determining that the Palmers Penguins are sexually dimorphic, I want to know if the different species differ in the degree of mass specific Sexual Size Dimorphism.</p>
</section>
</section>
<section id="analysis-of-sexual-size-dimorphism" class="level1">
<h1>Analysis of Sexual Size Dimorphism</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">'Sexual_Dimorphism.R'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To get a better idea of this discrepancy in Body Mass, I want to test the degree of sexual size dimorphism statistically. The goals here are to 1) illustrate that each of these three penguin species is significantly Sexually Dimorphic in body mass and 2) illustrate the relatively lower degree of dimorphism in the Chinstrap penguins. This second point will support the idea of the narrower body mass distribution in Chinstrap penguins reflecting reduced sexual size dimorphism. While this point might be self-evident, it is still interesting to note the correlation between sexual size dimorphism within a species and overall range in body mass.</p>
<p>To support my hypotheses, I first illustrate summary data on the differences in Body Mass and then test the significance of this difference with a Welch’s T-test. I replicate this process for each species.</p>
<section id="adelie-penguins" class="level3">
<h3 class="anchored" data-anchor-id="adelie-penguins">Adelie Penguins</h3>
<p>For the Adelie Penguins I first subset the species and remove NA values.</p>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<p>With the NA values removed, I first get an idea of the mean size differences between females and males. I installed the <em>report</em> package to help me summarize the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Subset the Species</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>Species<span class="sc">==</span><span class="st">"Adelie"</span>, ]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove the NA values</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d2[ <span class="sc">!</span><span class="fu">is.na</span>(d2<span class="sc">$</span><span class="st">"Sex"</span>), ]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co">#report data grouping by Sex and Body Mass</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>Adelie_report <span class="ot">&lt;-</span> <span class="fu">report_sample</span>(d2, <span class="at">group_by =</span> <span class="st">"Sex"</span>, <span class="at">select =</span> <span class="st">"Body Mass"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Adelie_report)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Descriptive Statistics

Variable            |    FEMALE (n=73) |      MALE (n=73) |    Total (n=146)
----------------------------------------------------------------------------
Mean Body Mass (SD) | 3368.84 (269.38) | 4043.49 (346.81) | 3706.16 (458.62)</code></pre>
</div>
</div>
<p>These means seem to pretty clearly indicate sexual dimorphism but I will run it through a Welch’s T-test to investigate statistical significance.</p>
</section>
<section id="t-test" class="level4">
<h4 class="anchored" data-anchor-id="t-test">T-test</h4>
<p>To test the means of each population (Male and Female) I need to filter the population into individual vectors. From there I can test the means through a t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"FEMALE"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>male <span class="ot">&lt;-</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"MALE"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a two sample t-test after filtering the data</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>t.test.Ad <span class="ot">&lt;-</span> <span class="fu">t.test</span>(female<span class="sc">$</span><span class="st">'Body Mass'</span>, male<span class="sc">$</span><span class="st">'Body Mass'</span>) </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>readttest <span class="ot">&lt;-</span> <span class="cf">function</span>( <span class="at">x =</span> t.test.Ad ){</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  tval <span class="ot">&lt;-</span> x<span class="sc">$</span>statistic</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  pval <span class="ot">&lt;-</span> x<span class="sc">$</span>p.value</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  fmean <span class="ot">&lt;-</span> x<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  mmean <span class="ot">&lt;-</span> x<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">data.frame</span>(<span class="st">"Females"</span><span class="ot">=</span> fmean, <span class="st">"Males"</span><span class="ot">=</span> mmean, <span class="st">"T-value"</span> <span class="ot">=</span> tval, <span class="st">"P-value"</span><span class="ot">=</span>pval))</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>Ad.table <span class="ot">&lt;-</span> <span class="fu">readttest</span>()</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Ad.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Females    Males   T.value     P.value
mean of x 3368.836 4043.493 -13.12629 6.40232e-26</code></pre>
</div>
</div>
<p>The p-value supports the significance of Sexual Size Dimorphism in Adelie Penguins. I will pay attention to the t-value (-13.126) for comparison with the other species’.</p>
</section>
</section>
<section id="gentoo-penguins" class="level3">
<h3 class="anchored" data-anchor-id="gentoo-penguins">Gentoo Penguins</h3>
<p>As noted above, the Gentoo penguins are subjected to the same round of tests as the Adelie penguins.</p>
<section id="summary-1" class="level4">
<h4 class="anchored" data-anchor-id="summary-1">Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Subset the Species and remove NA values </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>Species<span class="sc">==</span><span class="st">"Gentoo"</span>, ]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> d3[ <span class="sc">!</span><span class="fu">is.na</span>(d3<span class="sc">$</span><span class="st">"Sex"</span>), ]</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Same process as above</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>Gentoo_report <span class="ot">&lt;-</span> <span class="fu">report_sample</span>(d3, <span class="at">group_by =</span> <span class="st">"Sex"</span>, <span class="at">select =</span> <span class="st">"Body Mass"</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Gentoo_report)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Descriptive Statistics

Variable            |    FEMALE (n=55) |      MALE (n=61) |    Total (n=116)
----------------------------------------------------------------------------
Mean Body Mass (SD) | 4671.36 (285.39) | 5484.84 (313.16) | 5099.14 (505.80)</code></pre>
</div>
</div>
<p>This data seems to reflect an even greater degree of dimorphism than seen in Adelie Penguins. Next is the statstical test.</p>
</section>
<section id="t-test-1" class="level4">
<h4 class="anchored" data-anchor-id="t-test-1">T-test</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> d3 <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"FEMALE"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>male <span class="ot">&lt;-</span> d3 <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"MALE"</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the analysis</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>t.test.Gt <span class="ot">&lt;-</span> <span class="fu">t.test</span>(female<span class="sc">$</span><span class="st">'Body Mass'</span>, male<span class="sc">$</span><span class="st">'Body Mass'</span>) </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">readttest</span>(t.test.Gt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Females    Males   T.value      P.value
mean of x 4671.364 5484.836 -14.63759 6.078451e-28</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>Gt.table <span class="ot">&lt;-</span> <span class="fu">readttest</span>(t.test.Gt)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Gt.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Females    Males   T.value      P.value
mean of x 4671.364 5484.836 -14.63759 6.078451e-28</code></pre>
</div>
</div>
<p>Just as above, the p-value corroborates the violin plot distribution for Sexual Size Dimorphism. The t-value here (-14.638) is greater than that of Adelie (-13.126).</p>
<p><em>(I suggest that the value is greater despite the number actually being smaller. I have very little background in statistics but from what I have gathered, negative and positive values do not weigh on the interpretation of t-values).</em></p>
</section>
</section>
<section id="chinstrap-penguins" class="level3">
<h3 class="anchored" data-anchor-id="chinstrap-penguins">Chinstrap Penguins</h3>
<p>The final round of tests is run on the Chinstrap Penguins. My assumption is that both the p- and t- values will be smaller than those of the other two species.</p>
<section id="summary-2" class="level4">
<h4 class="anchored" data-anchor-id="summary-2">Summary</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Subset the Species</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>d4 <span class="ot">&lt;-</span> dat[dat<span class="sc">$</span>Species<span class="sc">==</span><span class="st">"Chinstrap"</span>, ]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co">#There is no need to remove NA values for this species</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Check by:</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>d4<span class="sc">$</span>Sex</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] FEMALE MALE   MALE   FEMALE MALE   FEMALE FEMALE MALE   FEMALE MALE  
[11] FEMALE MALE   FEMALE MALE   FEMALE MALE   MALE   FEMALE FEMALE MALE  
[21] FEMALE MALE   FEMALE MALE   FEMALE MALE   FEMALE MALE   FEMALE MALE  
[31] FEMALE MALE   FEMALE MALE   MALE   FEMALE FEMALE MALE   FEMALE MALE  
[41] MALE   FEMALE MALE   FEMALE FEMALE MALE   FEMALE MALE   MALE   FEMALE
[51] FEMALE MALE   FEMALE MALE   FEMALE MALE   FEMALE MALE   MALE   FEMALE
[61] MALE   FEMALE FEMALE MALE   FEMALE MALE   MALE   FEMALE
Levels: FEMALE MALE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Report on the data</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>Chinstrap_report <span class="ot">&lt;-</span> <span class="fu">report_sample</span>(d4, <span class="at">group_by =</span> <span class="st">"Sex"</span>, <span class="at">select =</span> <span class="st">"Body Mass"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Chinstrap_report)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Descriptive Statistics

Variable            |    FEMALE (n=34) |      MALE (n=34) |     Total (n=68)
----------------------------------------------------------------------------
Mean Body Mass (SD) | 3527.21 (285.33) | 3938.97 (362.14) | 3733.09 (384.34)</code></pre>
</div>
</div>
<p>It’s looking like a much narrower size difference.</p>
</section>
</section>
<section id="t-test-2" class="level3">
<h3 class="anchored" data-anchor-id="t-test-2">T-test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Filter the data</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>female <span class="ot">&lt;-</span> d4 <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"FEMALE"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>male <span class="ot">&lt;-</span> d4 <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"MALE"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the analysis</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>t.test.Cs <span class="ot">&lt;-</span> <span class="fu">t.test</span>(female<span class="sc">$</span><span class="st">'Body Mass'</span>, male<span class="sc">$</span><span class="st">'Body Mass'</span>) </span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="fu">readttest</span>(t.test.Cs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Females    Males   T.value      P.value
mean of x 3527.206 3938.971 -5.207734 2.264432e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Cs.table <span class="ot">&lt;-</span> <span class="fu">readttest</span>(t.test.Cs)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Cs.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Females    Males   T.value      P.value
mean of x 3527.206 3938.971 -5.207734 2.264432e-06</code></pre>
</div>
</div>
<p>The Chinstrap data represented here, while still showing a significance in dimorphism, shows a much lower t-value (-5.2077) than the two other species tested.</p>
</section>
<section id="sexual-size-dimorphism-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="sexual-size-dimorphism-conclusions">Sexual Size Dimorphism Conclusions</h3>
<p>It looks like the data supports my assumptions. The Chinstrap Penguins present much differently than the other species in terms of Sexual Dimorphism. Both the p- and t- values noticebly differed. I wanted to test the statistical difference between the t-test results, but I am not sure how to do that and I am too short on time for this assignment to figure it out. Regardless, suggesting that the overall reduced body mass range in Chinstrap Penguins relative to Adelie and Gentoo Penguins as an outcome of reduced sexual dimorphism seems like a plausible explanation.</p>
</section>
</section>
<section id="differentiating-between-adelie-and-chinstrap-penguins-on-dream-island" class="level1">
<h1>Differentiating between Adelie and Chinstrap penguins on Dream Island</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">read_chunk</span>(<span class="st">'Analysis_of_Variance.R'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Despite the differences in sexual dimorphism, the Chinstrap and Adelie Penguins seem to cluster closely in body mass. With their geographic overlap on Dream island, my next question concerns the morphological distinction between the two species. I consider whether, with the current available data, I can see the justification for differentiating the two populations as different species.</p>
<p>In examining photos of the two birds, the phenotypic differences are distinct. As a paleontologists, however, I do not often have the ability to examine soft tissue. Thus, for my own purposes, I’d like to see just how vague physical measurements can be in phylogenetic pursuits. I will acknowledge here that the measurements provided to us here were taken from specimens in the flesh, and so the results of this inquiry will not directly translate to my interests, but it is a starting point.</p>
<p>This final question seeks to determin if there are proportional differences in Flipper and Culmen dimensions for the two penguin species that might help to differentiate them.</p>
<p><em>I will note here that I did not come into this class with a statistics background. This is on the docket for next term. With that said, it seemed like one potential means of answering this question was to run a principal components analysis for each of the morphological variables given but omitting body mass. And so, this became my agenda.</em></p>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Chinstrap.jpg" class="img-fluid figure-img" data-width="30%"></p>
<p></p><figcaption class="figure-caption">Chinstrap Penguin</figcaption><p></p>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Adelie.jpg" class="img-fluid figure-img" data-width="50%"></p>
<p></p><figcaption class="figure-caption">Adelie Penguin</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
<section id="summary-data-for-adelie-and-chinstrap-penguins" class="level2">
<h2 class="anchored" data-anchor-id="summary-data-for-adelie-and-chinstrap-penguins">Summary Data for Adelie and Chinstrap Penguins</h2>
<p>I begin this process by removing Gentoo Penguins from the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Subset out Gentoo</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> dat[<span class="sc">!</span>dat<span class="sc">$</span>Species <span class="sc">==</span> <span class="st">"Gentoo"</span>, ] </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Drop unused levels from analysis (otherwise Gentoo continues to appear, just with no data)</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(b1)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Run a summary to get a quick look at the data means for each species</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"Delta"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="fu">report</span>(<span class="at">exclude =</span> <span class="st">"b1$Gentoo"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>()</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>c1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The data contains 219 observations, grouped by Species, of the following 7
variables:

- Adelie (n = 151):
  - Island: 3 levels, namely Biscoe (n = 44), Dream (n = 56) and Torgersen (n =
51)
  - Culmen Length: Mean = 38.79, SD = 2.66, range: [32.10, 46]
  - Culmen Depth: Mean = 18.35, SD = 1.22, range: [15.50, 21.50]
  - Flipper Length: Mean = 189.95, SD = 6.54, range: [172, 210]
  - Body Mass: Mean = 3700.66, SD = 458.57, range: [2850, 4775]
  - Sex: 2 levels, namely FEMALE (n = 73), MALE (n = 73) and missing (n = 5)

- Chinstrap (n = 68):
  - Island: 3 levels, namely Biscoe (n = 0), Dream (n = 68) and Torgersen (n = 0)
  - Culmen Length: Mean = 48.83, SD = 3.34, range: [40.90, 58]
  - Culmen Depth: Mean = 18.42, SD = 1.14, range: [16.40, 20.80]
  - Flipper Length: Mean = 195.82, SD = 7.13, range: [178, 212]
  - Body Mass: Mean = 3733.09, SD = 384.34, range: [2700, 4800]
  - Sex: 2 levels, namely FEMALE (n = 34) and MALE (n = 34)</code></pre>
</div>
</div>
<p>Before plotting each variable, I wanted to get a broad graphical look at the interspecific variation in the variables I hadn’t yet tested.</p>
<p>This task was accomplished by installing the GGally package. Using GGally, I generated bivariate plots for all morphological variables other than Body Mass.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(GGally)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the factor and continuous variables to plot. </span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Species, <span class="fu">ends_with</span>(<span class="st">"th"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  GGally<span class="sc">::</span><span class="fu">ggpairs</span>(<span class="fu">aes</span>(<span class="at">color =</span> Species)) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette=</span><span class="st">"Dark2"</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>c2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/Ad~Cs1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this set of images it looks like the starkest differences between the two penguin species are the Culmen Length and the Flipper Length, with Culmen Depth being fairly negligable. I want to be sure that these figures represent statistically powerful data though and so I run the Principal Components analysis to determine which variables are most significant.</p>
<section id="principal-components-analysis" class="level3">
<h3 class="anchored" data-anchor-id="principal-components-analysis">Principal Components Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove Body Mass by selecting for other variables only.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Run Principal Components analysis with princomp function. </span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>b2 <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="st">"Culmen Length"</span>, <span class="st">"Culmen Depth"</span>, <span class="st">"Flipper Length"</span>) </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>b2.pc <span class="ot">&lt;-</span> <span class="fu">princomp</span>(b2, <span class="at">scores=</span>T)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(b2.pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          Comp.1    Comp.2     Comp.3
Standard deviation     8.0077579 4.2638789 1.09283532
Proportion of Variance 0.7679623 0.2177347 0.01430301
Cumulative Proportion  0.7679623 0.9856970 1.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pcsum <span class="ot">&lt;-</span> <span class="fu">summary</span>(b2.pc)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pcsum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          Comp.1    Comp.2     Comp.3
Standard deviation     8.0077579 4.2638789 1.09283532
Proportion of Variance 0.7679623 0.2177347 0.01430301
Cumulative Proportion  0.7679623 0.9856970 1.00000000</code></pre>
</div>
</div>
<p>This analysis shows pretty clearly that the most variation is found in pc1 (~77%) with a fairly steep drop with pc2 (~22%) and negligable scores for pc3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Illustrate PC Loadings</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">loadings</span>(b2.pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
               Comp.1 Comp.2 Comp.3
Culmen Length   0.504  0.863       
Culmen Depth                 -0.998
Flipper Length  0.861 -0.505       

               Comp.1 Comp.2 Comp.3
SS loadings     1.000  1.000  1.000
Proportion Var  0.333  0.333  0.333
Cumulative Var  0.333  0.667  1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>pcload <span class="ot">&lt;-</span> <span class="fu">loadings</span>(b2.pc)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pcload)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
               Comp.1 Comp.2 Comp.3
Culmen Length   0.504  0.863       
Culmen Depth                 -0.998
Flipper Length  0.861 -0.505       

               Comp.1 Comp.2 Comp.3
SS loadings     1.000  1.000  1.000
Proportion Var  0.333  0.333  0.333
Cumulative Var  0.333  0.667  1.000</code></pre>
</div>
</div>
<p>PC1 illustrates that most of the variation with the sample is found in Flipper Length. Second to that is the distribution of Culmen Length Values. Importantly, it does not seem from this that Culmen Depth factors into the variation within this population.</p>
<p>Because Culmen Depth is a negligable variable in this analysis, I focus on pc1 and pc2. The plot shows variation and when demarcating the species, shows distinct groupings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Because Culmen Depth is a negligable variable in this analysis, I focus on pc1 and pc2.</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot PC1~PC2</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>pc1 <span class="ot">&lt;-</span> b2.pc<span class="sc">$</span>scores[,<span class="dv">1</span>]</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>pc2 <span class="ot">&lt;-</span> b2.pc<span class="sc">$</span>scores[,<span class="dv">2</span>]</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>pc3 <span class="ot">&lt;-</span> b2.pc<span class="sc">$</span>scores[,<span class="dv">3</span>]</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pc2 <span class="sc">~</span> pc1, <span class="at">col=</span>b1<span class="sc">$</span>Species, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/Ad~Cs4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ANOVA</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Illustrate variance in Culmen Length</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Generate dataset mean value and specific species means</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This illustrates that there are distinct proportional differences in Culmen Length and Flipper Length between the two species. Finally, I will run an ANOVA for these variables.</p>
</section>
<section id="analysis-of-variance" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-variance">Analysis of Variance</h3>
<p>My last step is to investigate how much these variables (Culmen Length and Flipper Length) vary by species. I begin with Culmen Length.</p>
<section id="culmen-length-variance" class="level4">
<h4 class="anchored" data-anchor-id="culmen-length-variance">Culmen Length Variance</h4>
<p>My goal is to identify whether the two species are significantly different in Culmen Length. I start by generating an index column for the data. I calculate the mean of the scores for the whole dataset as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Scale by individual data points by assigning IDs to each.</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(b1, <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(b1<span class="sc">$</span>Species))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Establish group mean</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">mean</span>(b1<span class="sc">$</span><span class="st">'Culmen Length'</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The next step was to differentiate the mean Culmen Length value for each species under investigation. I worked on this for A LONG time and could not get it to work. I followed the example given in the Univariate Stats lecture, followed notes from an in person meeting with the professor, and followed the instructions from multiple online sources. I altered the code below in many ways but could never get r to generate separate species means. At the end of the day, I had to move forward. This ultimately changes how my plots turned out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This is supposed to differentiate the species means</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co">#CAN'T GET TO WORK</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>spmeans  <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span> </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summarise</span>(</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">sl =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Culmen Length</span><span class="st">`</span>),</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">n =</span> <span class="fu">length</span>(id),</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">minid =</span> <span class="fu">min</span>(id),</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">maxid =</span> <span class="fu">max</span>(id)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>spmeans</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  Species      sl     n minid maxid
  &lt;fct&gt;     &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
1 Adelie     38.8   151     1   151
2 Chinstrap  48.8    68   152   219</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Species means are only representing the entire sample. Can't get it to differentiate.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Proceed anyways</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Merge the means into the original dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I first plot the data for the whole assemblage. Especially when embedding the variance lines, there is a pretty distinct difference in how the data is clustered.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">merge</span>(b1, spmeans)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot data with means</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>( <span class="at">x =</span> b1<span class="sc">$</span>id, <span class="at">y =</span> b1<span class="sc">$</span><span class="st">'Culmen Length'</span>, <span class="at">group=</span>Species)) </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> z <span class="sc">+</span> <span class="fu">geom_point</span>( <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>( <span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(b1<span class="sc">$</span><span class="st">'Culmen Length'</span>)) ) <span class="sc">+</span> </span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( <span class="at">data=</span>l, <span class="fu">aes</span>( <span class="at">x =</span> l<span class="sc">$</span>id, <span class="at">y =</span> l<span class="sc">$</span><span class="st">'Culmen Length'</span>, <span class="at">xend =</span> id, <span class="at">yend =</span> sl), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>s  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/anovaCL3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The next step was to illustrate the species differences. I was successful in showing where the different species lie on the plot but, again, I could not illustrate the differences in Culmen Length mean for each species.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Highlight the species differences in variance from mean</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> z <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>(<span class="at">data=</span>spmeans, <span class="fu">aes</span>(<span class="at">x =</span> minid, <span class="at">y =</span> sl, <span class="at">xend =</span> maxid, <span class="at">yend =</span> sl, <span class="at">group=</span>Species)) <span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>( <span class="at">data=</span>l, <span class="fu">aes</span>( <span class="at">x =</span> id, <span class="at">y =</span> l<span class="sc">$</span><span class="st">"Culmen Length"</span>, <span class="at">xend =</span> id, <span class="at">yend =</span> sl, <span class="at">color=</span>Species), <span class="at">lty =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Culmen Variation"</span>,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="at">x=</span> <span class="st">"ID"</span>, <span class="at">y =</span> <span class="st">"Culmen Length"</span>) </span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>r</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/anovaCL4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While my plot did not work out quite the way I wanted it to, I was successful in illustrating that the Adelie and Chinstrap penguins significantly differ in the distribution of Culmen Length values.</p>
<p>This is highlighted statistically through the ANOVA below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Run ANOVA to establish statistical difference</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>lm.fit.c <span class="ot">&lt;-</span> <span class="fu">lm</span>(b1<span class="sc">$</span><span class="st">'Culmen Length'</span> <span class="sc">~</span> b1<span class="sc">$</span>Species, <span class="at">data=</span>b1)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>anova.table.c <span class="ot">&lt;-</span> <span class="fu">anova</span>(lm.fit.c)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(anova.table.c) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Species"</span>, <span class="st">"Residuals"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova.table.c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: b1$"Culmen Length"
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Species     1 4728.5  4728.5  566.53 &lt; 2.2e-16 ***
Residuals 217 1811.2     8.3                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>I need a lot of work on my statistics knowledge, but it looks like the pr(&gt;F) value supports a statistically significant difference between the two groups.</p>
</section>
<section id="flipper-length-variance" class="level4">
<h4 class="anchored" data-anchor-id="flipper-length-variance">Flipper Length Variance</h4>
<p>The above analysis aligns with what I was expecting from the bivariate plots above and the Principal Components Analysis. The next variable highlighted by the PCA is Flipper Length. This value was said to represnt the most variation in the two species as a singular data set. My goal here is to determine whether the species can be easily differentiated along this range of variation.</p>
<p>I start by attempting to parse out the mean values for Flipper Length for each species. This effort, as in the above analysis, did not work out…and I can’t figure out why.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the data IDs from above. Didn't use the yhat mean. No need to bring it back. </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Establish species mean differences</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co">#CAN'T GET TO WORK</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>spmeans2 <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(b1<span class="sc">$</span>Species) <span class="sc">%&gt;%</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sl =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">Flipper Length</span><span class="st">`</span>),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">length</span>(id),</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">minid =</span> <span class="fu">min</span>(id),</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxid =</span> <span class="fu">max</span>(id),</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>spmeans2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  `b1$Species`    sl     n minid maxid
  &lt;fct&gt;        &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
1 Adelie        190.   151     1   151
2 Chinstrap     196.    68   152   219</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Species means are only representing the entire sample. Can't get it to differentiate.</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Proceed anyways</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, the means map the same (same for the larger dataset mean) for each species. It believe this is why my plots below will not segment along species means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Merge the means into the original dataset</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">merge</span>(b1, spmeans2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I run through the same plotting process for Flipper Length as I did for Culmen Length.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot data with means.</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>o <span class="ot">&lt;-</span> b1 <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>( <span class="at">x =</span> b1<span class="sc">$</span>id, <span class="at">y =</span> b1<span class="sc">$</span><span class="st">'Flipper Length'</span>)) </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> o <span class="sc">+</span> <span class="fu">geom_point</span>( <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>( <span class="fu">aes</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(b1<span class="sc">$</span><span class="st">'Flipper Length'</span>)) ) <span class="sc">+</span> </span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>( <span class="at">data=</span>y, <span class="fu">aes</span>( <span class="at">x =</span> id, <span class="at">y =</span> y<span class="sc">$</span><span class="st">'Flipper Length'</span>, <span class="at">xend =</span> id, <span class="at">yend =</span> sl), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>t  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/anovaFL3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Despite getting the above warning on all of these plots, the analysis in r does not work if I follow the suggestion. Thus, I have to keep the y$“FLipper Length” syntax.</p>
<p>By differentiating the species by line color in the below plot, I could again illustrate each species’ relationship with the mean value of Flipper Length. This analysis, however, looks much different than the prior one. While there is a noticable difference in where the species means would lie if differentiated, it is a much smaller difference than with Culmen Length.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Highligh the species differences in variance from mean</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> o <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>(<span class="at">data=</span>spmeans2, <span class="fu">aes</span>(<span class="at">x =</span> minid, <span class="at">y =</span> sl, <span class="at">xend =</span> maxid, <span class="at">yend =</span> sl)) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>( <span class="at">data=</span>y, <span class="fu">aes</span>( <span class="at">x =</span> id, <span class="at">y =</span> y<span class="sc">$</span><span class="st">"Flipper Length"</span>, <span class="at">xend =</span> id, <span class="at">yend =</span> sl, <span class="at">color=</span>Species), <span class="at">lty =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Flipper Variation"</span>,</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="at">x=</span> <span class="st">"ID"</span>, <span class="at">y =</span> <span class="st">"Flipper Length"</span>)</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="exploratory_analysis_files/figure-html/anovaFL4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I run the ANOVA and still see a significant statistical difference. I need to brush up on my chops a bit and figure out how to interpret this in a way that corroborates my interpretation from the plots. Saying that both of these variables are significantly different in each species is fine, but one variable seems to be clearly more meaningful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Run anova to establish statistical significance</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>lm.fit.f <span class="ot">&lt;-</span> <span class="fu">lm</span>(b1<span class="sc">$</span><span class="st">'Flipper Length'</span> <span class="sc">~</span> b1<span class="sc">$</span>Species, <span class="at">data=</span>b1)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>anova.table.f <span class="ot">&lt;-</span> <span class="fu">anova</span>(lm.fit.f)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(anova.table.f) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Species"</span>, <span class="st">"Residuals"</span>)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(anova.table.f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: b1$"Flipper Length"
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Species     1 1615.5 1615.48  35.689 9.379e-09 ***
Residuals 217 9822.6   45.27                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>I would end this analysis by suggesting that besides Sexual Size Dimorphism, the Adelie and Chinstrap penguins can be differentiated through morphometric data by means of examining the Culmen Length. I am assuming here that the difference in flipper length between the two species is more a product of overall size difference (Flipper Length correlating with Body Mass). I know there are additional ways of testing this but that will be a goal for further research.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>